parser: babel-eslint
globals:
  graphql: true
plugins:
- prettier
extends:
- airbnb
- "@cherihung/gatsby"
- prettier
- prettier/react
rules:
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jsx-a11y/href-no-hash: 'off'
  babel/object-curly-spacing: 'off'
  react/jsx-filename-extension: 'off'
  react/no-danger: 'off'
